#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration
#it displays Best School and then Hi on a new line.
num=0
while [ $num -lt 10 ]
do
    if [ $num = 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((num++))
done