#!/usr/bin/env bash
#script that displays
#The content of the current directory
#In a list format
list="$(ls)"
for i in $list;
do
    name_after_dash=$(echo "$i" | cut -d '-' -f 2-)
    echo "$name_after_dash"
done